version: 0.0
os: linux
files:
  - source: ./
    destination: /var/www
permissions:
  - object: /var/www
    owner: ec2-user
hooks:
  BeforeInstall:
    - location: none.sh
      timeout: 3600
      runas: ec2-user
  AfterInstall:
    - location: launch.sh
      timeout: 3600
      runas: ec2-user
  ApplicationStart:
    - location: write_deploy_info.sh
      timeout: 3600
      runas: ec2-user
