version: 0.0
os: linux
files:
  - source: ./
    destination: /var/www
    overwrite: yes
permissions:
  - object: /var/www
    owner: ec2-user
hooks:
  AfterInstall:
    - location: launch.sh
      timeout: 3600
      runas: ec2-user

